apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::$AWS_ACCOUNT_ID:role/EKSAssumeRole
      username: EKSAssumeRole
  mapUsers: | 
    - groups:
      - system:masters
      userarn: arn:aws:iam::$AWS_ACCOUNT_ID:user/$AWS_USER_NAME
      username: $AWS_USER_NAME
      