apiVersion: v1
kind: ServiceAccount
metadata:
  name: k-bnt-15
  labels:
    app.kubernetes.io/name: k-bnt-15
    app.kubernetes.io/instance: k-bnt-15-$INSTANCE_VERSION
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: GitHub-Actions
    app.kubernetes.io/component: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$AWS_ACCOUNT_ID:role/$AWS_IAM_SERVICE_ROLE_NAME

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k-bnt-15
  labels:
    app.kubernetes.io/name: k-bnt-15
    app.kubernetes.io/instance: k-bnt-15-$INSTANCE_VERSION
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: GitHub-Actions
    app.kubernetes.io/component: backend  
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k-bnt-15
subjects:
- kind: ServiceAccount
  name: k-bnt-15    
