apiVersion: v1
kind: Secret
metadata:
  name: secrets   
  labels:
    app.kubernetes.io/name: k-bnt-15
    app.kubernetes.io/instance: k-bnt-15-$INSTANCE_VERSION
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: GitHub-Actions
    app.kubernetes.io/component: backend
type: Opaque
data:
  AWS_REGION: $AWS_REGION
  AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_RDS_URL: $AWS_RDS_URL
  AWS_RDS_USERNAME: $AWS_RDS_USERNAME
  AWS_RDS_PASSWORD: $AWS_RDS_PASSWORD 
