apiVersion: v1
kind: Service
metadata:
  name: k-bnt-15
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.bnt-15.kr
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:$AWS_CM_REGION:$AWS_ACCOUNT_ID:certificate/$AWS_CM_ID
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https    
  labels:
    app.kubernetes.io/name: k-bnt-15
    app.kubernetes.io/instance: k-bnt-15-$INSTANCE_VERSION
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: GitHub-Actions
    app.kubernetes.io/component: backend
spec:
  selector:
    app: k-bnt-15
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
