CREATE TABLE synonym (
       synonym_id bigint generated BY DEFAULT AS IDENTITY,
        question_id bigint NOT NULL,
        synonym_word VARCHAR(255) NOT NULL,
        PRIMARY KEY (synonym_id)
    );